### ISSUE TITLE
Node version incompatible

### ISSUE THREAD

**Issue by spacemeowx2** [blesstosam/weibo-node-api#1]
使用 `yarn` 安装的时候提示

```
error weibo-node-api@1.0.0: The engine "node" is incompatible with this module. Expected version "10.16.3". Got "12.13.0"
```

我理解应该是限定了最低版本而不是锁定10.16.3版本

https://github.com/blesstosam/weibo-node-api/blob/3c7c0d1c5be060daec27d44ac6691a3a63a81f83/package.json#L98

**Comment by pboymt** [comment]
package.json里面是直接锁定版本了……写成`>=10.16.3`才能正常

**Comment by blesstosam** [comment]
https://github.com/blesstosam/weibo-node-api/commit/2e965ad511f917477c7c9e24e0be8c9e83a3b44c
